# Generated by Django 4.1.5 on 2023-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="show_email",
        ),
        migrations.AddField(
            model_name="user",
            name="show_website",
            field=models.BooleanField(
                default=False,
                help_text="Show website on personal page?",
                verbose_name="Show Website",
            ),
        ),
    ]
