# Generated by Django 4.1.5 on 2023-01-21 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_bio_user_image_user_website"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="avatar",
        ),
    ]
