# Generated by Django 4.1.5 on 2023-02-24 02:21

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Your user avatar.",
                null=True,
                upload_to=user.models.user_avatar_path,
                verbose_name="User Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(
                blank=True,
                help_text="Say a little something about yourself.",
                max_length=255,
                null=True,
                verbose_name="User Bio",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Your personal website.",
                max_length=255,
                null=True,
                verbose_name="User Website",
            ),
        ),
    ]
