# Generated by Django 4.1.5 on 2023-02-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_avatar_alter_user_bio_alter_user_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Required. Please enter a valid email.",
                max_length=254,
                verbose_name="email address",
            ),
        ),
    ]
