# Generated by Django 4.1.5 on 2023-02-25 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the post.", max_length=200),
                ),
                ("text", models.TextField(help_text="Text of the post.")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image uploaded with post.",
                        null=True,
                        upload_to="images/%Y/%m/%d",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date & Time Created",
                    ),
                ),
                (
                    "last_edited",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date & Time Last Edited",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Author of the post.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
