# Generated by Django 4.1.5 on 2023-03-04 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the post.", max_length=200),
                ),
                ("text", models.TextField(help_text="Text of the post.")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Image uploaded with post.",
                        null=True,
                        upload_to="images/%Y/%m/%d",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date & Time Created",
                    ),
                ),
                (
                    "last_edited",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date & Time Last Edited"
                    ),
                ),
            ],
        ),
    ]
